apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
    labels:
      app: member
      name: member
  spec:
  replicas: 1
    selector:
      matchLabels:
          app: member
        strategy: {}
    template:
      metadata:
          creationTimestamp: null
            labels:
              app: member
            spec:
          containers:
            - image: cst8277/member-app:latest
              name: member-app
                resources: {}
        status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
    labels:
      app: member
      name: member
  spec:
  ports:
    - name: 8088-8088
      port: 8088
        protocol: TCP
        targetPort: 8088
      selector:
      app: member
      type: NodePort
  status:
  loadBalancer: {}
  