apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
    labels:
      app: subscription
      name: subscription
  spec:
  replicas: 1
    selector:
      matchLabels:
          app: subscription
        strategy: {}
    template:
      metadata:
          creationTimestamp: null
            labels:
              app: subscription
            spec:
          containers:
            - image: cst8277/subscription-app:latest
              name: subscription-app
                resources: {}
        status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
    labels:
      app: subscription
      name: subscription
  spec:
  ports:
    - name: 8086-8086
      port: 8086
        protocol: TCP
        targetPort: 8086
      selector:
      app: subscription
      type: NodePort
  status:
  loadBalancer: {}
  