apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbs-deployment
  labels:
    app: dbs
spec:
  selector:
    matchLabels:
      app: dbs
  template:
    metadata:
      labels:
        app: dbs
    spec:
      containers:
        - name: dbs
          imagePullPolicy: "IfNotPresent"
          image: qweqwe531/dbs:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              ephemeral-storage: "2Gi"
            limits:
              ephemeral-storage: "4Gi"
