apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
    labels:
      app: message
      name: message
  spec:
  replicas: 1
    selector:
      matchLabels:
          app: message
        strategy: {}
    template:
      metadata:
          creationTimestamp: null
            labels:
              app: message
            spec:
          containers:
            - image: cst8277/message-app:latest
              name: message-app
                resources: {}
        status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
    labels:
      app: message
      name: message
  spec:
  ports:
    - name: 8087-8087
      port: 8087
        protocol: TCP
        targetPort: 8087
      selector:
      app: message
      type: NodePort
  status:
  loadBalancer: {}
  