server:
  port: 8085
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/twit"
    username: "root"
    password: "pass"
  jpa:
    hibernate:
      ddl-auto: "create-drop"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
